Feat: 일정관리 페이지 구현
la-vie-est-belle-application/Client pull request #20
Opened 2024-05-08 13:54 UTC by dv-yeop920

### ⛳️ Task

- 헤더 컴포넌트 구현
- 달력 컴포넌트 구현
- 일정관리 페이지 구현
- VAC 패턴으로 리팩토링
- 동적으로 스타일 변하도록 수정

### ✍️ Note
초안 완성
### ⚡️ Test

### 📸 Screenshot

### 📎 Reference

2024-05-08 16:40 UTC, tkyoun0421 requested changes
오타만 수정해주세요! 고생하셨습니다 👍

2024-05-08 16:40 UTC, tkyoun0421 commented on src/pages/ScheduleManage.tsx
> +export default ScheduleMnage;
오타가 있는 것 같아요!

2024-05-08 17:10 UTC, dv-yeop920 commented on src/pages/ScheduleManage.tsx
> +export default ScheduleMnage;
오타 수정해서 다시 올렸습니다 !

2024-05-09 04:19 UTC, tkyoun0421 approved these changes
고생하셨습니다~~ 👍 👍

2024-05-09 04:19 UTC, merged